version: "3.9"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules   # ← コンテナ専用に保持
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development

volumes:
  frontend_node_modules: {}